# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PediatricPancreas_Storyboard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PediatricPancreas_Storyboard
  
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'PSPDFKit', podspec: 'https://customers.pspdfkit.com/cocoapods/TRIAL-ydBek_93rV-QYfEC_opiqLkbbUgRaNEpVdZA73Qalp3c7D1b1rvQ6Dm-jqdE4sR1ezgQGno43b4l5Iq8m-0e8rzl2bx4w9cVOpgUOk17kmg/latest.podspec'
  
end
